cloud-bulldozer/scale-ci-deploy

- OCP-4.X/roles/post-config/tasks/main.yml
Due to uperf not specifing the port range it will use for flags we need to open a large number of ports to permit HostNetwork benchmarks.
See pbench issue #1238
https://github.com/distributed-system-analysis/pbench/issues/1238
> Correcting uperf port range for HostNetwork

- OCP-4.X/roles/quickstart/tasks/main.yml
The tasks are no longer needed as we are using workloads framework
and clusterloader is part of the scale-ci-workload image.
> Cleanup quickstart role tasks

- OCP-4.X/roles/install-on-aws/templates/install-config.yaml.j2
On systems where it is not possible to upgrade jinja2 installer will fail as module
`tojson` is not part of jinja installation. This is case for RHEL 7/Centos 7 which deliver
python36-jinja2-2.8.1-2.el7.noarch
python-jinja2-2.7.2-4.el7.noarch
eg ansible issue : https://github.com/ansible/ansible/issues/25381
Fedora 30 is not affected with this problem
> change from tojson to to_json - for systems where newer version of jinja is not available.

- OCP-4.X/install-on-gcp.yml
- OCP-4.X/roles/cleanup-on-gcp/tasks/main.yml
- OCP-4.X/roles/install-on-gcp/files/google-cloud-sdk.repo
- OCP-4.X/roles/install-on-gcp/tasks/main.yml
- OCP-4.X/roles/install-on-gcp/templates/install-config.yaml.j2
- OCP-4.X/roles/install-on-gcp/templates/registry_auth.j2
- OCP-4.X/roles/post-config-on-gcp/tasks/main.yml
- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/roles/post-install/templates/gcp-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/gcp-workload-node-machineset.yml.j2
- OCP-4.X/vars/install-on-gcp.yml
- docs/README.md
- docs/ocp4_gcp.md
This commit:
- Adds install role to install OCP 4.x on GCP.
- Adds post install roles to create infra, workload nodes and configure
the cluster to be able to run workloads.
- Adds a readme with the instructions.
> Add support to install ocp on google cloud

- OCP-4.X/roles/install-on-aws/tasks/main.yml
- OCP-4.X/roles/install-on-azure/tasks/main.yml
- OCP-4.X/roles/install-on-gcp/tasks/main.yml
- OCP-4.X/roles/install-on-osp/tasks/main.yml
Copying the files onto the local host will enable us to store them
as artifacts when we run the job from a jenkins slave.
> Copy install log and kubeconfig to store them as artifacts

- OCP-4.X/roles/install-on-aws/tasks/main.yml
- OCP-4.X/roles/install-on-azure/tasks/main.yml
- OCP-4.X/roles/install-on-gcp/tasks/main.yml
- OCP-4.X/roles/install-on-osp/tasks/main.yml
- OCP-4.X/vars/install-on-aws.yml
- OCP-4.X/vars/install-on-azure.yml
- OCP-4.X/vars/install-on-gcp.yml
- OCP-4.X/vars/install-on-osp.yml
- docs/ocp4_aws.md
- docs/ocp4_azure.md
- docs/ocp4_gcp.md
- docs/ocp4_osp.md
This commits enables us to use the openshift-install binary extracted
from a provided url in addition to extracting it from the provided
image.
Fixes https://github.com/openshift-scale/scale-ci-deploy/issues/40
> Add support to install clusters using binary extracted from url

- OCP-4.X/roles/install-on-aws/templates/install-config.yaml.j2
- OCP-4.X/roles/install-on-azure/templates/install-config.yaml.j2
- OCP-4.X/roles/install-on-gcp/templates/install-config.yaml.j2
- OCP-4.X/vars/install-on-aws.yml
- OCP-4.X/vars/install-on-azure.yml
- OCP-4.X/vars/install-on-gcp.yml
- docs/ocp4_aws.md
- docs/ocp4_azure.md
- docs/ocp4_gcp.md
This will give us the ability to toggle between OVS and OVN for cluster deployment. @jtaleric @chaitanyaenr
> Deploy OVN from scale-ci-deploy

- OCP-4.X/roles/install-on-azure/tasks/main.yml
- OCP-4.X/roles/install-on-gcp/tasks/main.yml
- OCP-4.X/roles/install-on-osp/tasks/main.yml
Variables will be consistent across all the cloud/osp deployments.  
To provide the binary, use env var of OPENSHIFT_INSTALL_BINARY_URL 
@chaitanyaenr
> make vars consistent with tasks

- OCP-4.X/roles/install-on-aws/tasks/main.yml
- OCP-4.X/roles/install-on-azure/tasks/main.yml
- OCP-4.X/roles/install-on-gcp/tasks/main.yml
- OCP-4.X/roles/install-on-osp/tasks/main.yml
This will keep the host clean by storing the artifacts in the playbook dir
instead of users home directory.
> Use playbook_dir instead of ansible_user_dir

- OCP-4.X/roles/post-install/files/version-patch-override.yaml
- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/vars/install-on-azure.yml
- docs/ocp4_azure.md
This commit:
- Adds support to disable cluster-monitoring-operator
from being controlled by cvo to be able to run the monitoring
components on dedicated infra nodes.
- Changes the default storage class to managed_premium as that's the
default storage class avaiable for OCP 4.3 installs.
> Cluster monitoring operator changes for OCP 4.3

- OCP-4.X/roles/post-install/tasks/main.yml
Added missing .stdout when clustername isn't provided
for sincgars.
> add missing stdout for sincgars

- OCP-4.X/roles/post-install/tasks/main.yml
Steering the cluster-monitoring-operator needs overriding CVO which
leads to upgrade failures, so we just steer the monitoring components
including prometheus, alertmanager, grafana and kube-state metrics by
modifying the cluster-monitoring-config ConfigMap.
> Avoid steering cluster-monitoring-operator onto infra nodes

- OCP-4.X/roles/node-debug-config/tasks/main.yml
the ".dest" part was missing causing python errors when executed.
> Fixed item.dest in OCP-4.X role node-debug-config in task Copy the kubeconfig to node from specific directory

- OCP-4.X/build-info.yml
- OCP-4.X/vars/build-info.yml
This commit:
- Adds a playbook which queries for the build info from the provided
info and dumps it to a specified destination. The use case for adding
this is to query the umb message for the OCP green nighltly builds
and update the file in a location accessible over http. This captured
content can be used to trigger OCP installs on a nightly basis.
- This also adds/updates a status file with PROCEED/STOP signal which can
be used by the OCP install jobs to decide whether to proceed with the build
or not. The status file is updated with the PROCEED if there's a mismatch
between the payloads or when we don't have info about the previous payload
and it's updated with STOP signal if the previous and current payload captured
from the UMB message are the same. We can use this logic in the …
> Add support to capture OCP build info

- OCP-4.X/roles/cleanup-on-aws/tasks/main.yml
- OCP-4.X/roles/cleanup-on-azure/tasks/main.yml
- OCP-4.X/roles/cleanup-on-gcp/tasks/main.yml
This commit enables us always enable cleanup irrespective of whether
a cluster is running or not. It checks if a cluster is running and
runs the destroy operation only when it exists.
Fixes https://github.com/openshift-scale/scale-ci-deploy/issues/59
> Check the cluster status before attempting destroy

- OCP-4.X/roles/post-install/templates/aws-workload-node-machineset.yml.j2
The cluster_name was needed to be part of the machineset name in order for destroy cluster functionality to succeed, otherwise workload node was not deleted and our automated jobs to destroy clusters were failing.
> Added cluster_name.stdout prefix to machineset name

- OCP-4.X/roles/post-install/templates/aws-workload-node-machineset.yml.j2
This will help with reliability of results by steering workload generator off of the same az that infra nodes are located on.
> Move workload node to an availability zone outside of infra nodes

- OCP-4.X/build-info.yml
This commits adds the ability to the build trigger to check the job
status which can used to track the status of the individual jobs in
the pipeline to report failures which we can use to stop the trigger
from proceeding with the cluster rebuild. This way we can investigate
what went wrong. If the job.status file is not found or set to true,
the cluster rebuild just depends on signal obtained from comparing
current vs previous builds.
> Add ability to build trigger to check job status

- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/roles/post-install/templates/cerberus.j2
- OCP-4.X/vars/install-on-aws.yml
- OCP-4.X/vars/install-on-azure.yml
- OCP-4.X/vars/install-on-gcp.yml
- OCP-4.X/vars/install-on-osp.yml
- docs/ocp4_aws.md
- docs/ocp4_azure.md
- docs/ocp4_gcp.md
- docs/ocp4_osp.md
This commit is a first step towards #64 
This commit enables the containerized version of cerberus to be
installed and enabled after the OCP installation.
This commit is based on `https://github.com/openshift-scale/cerberus/pull/38`
> Added support to enable cerberus

- OCP-4.X/install-on-aws.yml
- OCP-4.X/install-on-azure.yml
- OCP-4.X/install-on-gcp.yml
- OCP-4.X/install-on-osp.yml
- OCP-4.X/roles/cerberus/tasks/main.yml
- OCP-4.X/roles/cerberus_install/tasks/main.yml
- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/scale.yml
- OCP-4.X/upgrade.yml
- OCP-4.X/vars/install-on-aws.yml
- OCP-4.X/vars/install-on-azure.yml
- OCP-4.X/vars/install-on-gcp.yml
- OCP-4.X/vars/install-on-osp.yml
- OCP-4.X/vars/scale.yml
- OCP-4.X/vars/upgrade.yml
- docs/README.md
- docs/ocp4_aws.md
- docs/ocp4_azure.md
- docs/ocp4_gcp.md
- docs/ocp4_osp.md
- docs/ocp4_scale.md
- docs/ocp4_upgrade.md
This adds an optional CERBERUS_URL variable that can be passed to all install/upgrade/scale jobs. If enabled then it will check the status of the cluster prior and post activity. It fails if Cerberus returns False during any of the checks
> Adding Cerberus integration

- OCP-4.X/roles/install-on-gcp/tasks/main.yml
- OCP-4.X/roles/post-config-on-gcp/tasks/main.yml
- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/roles/post-install/templates/gcp-ssd-sc.yml.j2
- OCP-4.X/vars/install-on-gcp.yml
1. update default sc to standard for the monitoring stack related pv
2. allow for install of pd-ssd sc class
3. export credentials instead of doing a login
> minor fixes to allow for gcp to work

- OCP-4.X/roles/install-on-gcp/tasks/main.yml
- OCP-4.X/roles/post-config-on-gcp/tasks/main.yml
copy google sdk file from jenkins-slave to jump host (to avoid https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/ATS-SCALE-CI-TEST/184/console)
Firewall rule names have the cluster name pre fixed instead of post fixed so that cleanup is able to delete these firewall rules
> get google-sdk file from absolute path

- OCP-4.X/roles/cerberus_install/tasks/main.yml
- OCP-4.X/roles/cerberus_install/templates/cerberus.j2
- OCP-4.X/vars/install-on-aws.yml
- OCP-4.X/vars/install-on-azure.yml
- OCP-4.X/vars/install-on-gcp.yml
- OCP-4.X/vars/install-on-osp.yml
This commit also updates the cerberus config with the latest
supported options and pauses for 120 seconds for the cerberus
to run an iteration to check the health status before using the
exposed signal to verify if the installed cluster is healthy.
> Fix cerberus config template location

- OCP-4.X/build-info.yml
- OCP-4.X/vars/build-info.yml
This commit enables user to pass either an url or the umb message
containing the payload info.
> Scrape payload info from url in addition to umb message

- OCP-4.X/install-on-aws.yml
- OCP-4.X/roles/cleanup-on-aws/tasks/main.yml
- OCP-4.X/roles/cleanup-on-azure/tasks/main.yml
- OCP-4.X/roles/cleanup-on-gcp/tasks/main.yml
Fixes #81  
There are times when the cluster is pruned and the artifact (scale-ci-aws, bin) direcotries in scale-ci-deploy are not cleaned up. This PR will check if the cluster is running and only then will execute `destroy`. If the cluster is not running it will simply remove the artifact directories.
@chaitanyaenr
> check for cluster status and artifacts before cleanup

- OCP-4.X/roles/post-config-on-azure/tasks/main.yml
change priority of scale-ci-ssh to 103 as 
```
root@: ~ #  az network nsg rule create -g  perfciazure-xxxxx-rg --name scale-ci-ssh --nsg-name perfciazure-xxxxx-nsg --priority 101 --access Allow --description "scale-ci allow ssh" --protocol Tcp --destination-port-ranges "22"
Security rule apiserver_in conflicts with rule scale-ci-ssh. Rules cannot have the same Priority and Direction.
```
grep for nsg as
```
root@: ~ # az network nsg list -g perfciazure-xxxxx-rg --query "[].name" -o tsv | grep "nsg" 
perfciazure-xxxxx-nsg
```
and add `openshift_expiryDate` to extend the expiry from 2 days to 40 days
@chaitanyaenr @dry923
> extend the life of Azure cluster and minor fixes

- OCP-4.X/roles/cleanup-on-aws/tasks/main.yml
- OCP-4.X/roles/cleanup-on-azure/tasks/main.yml
- OCP-4.X/roles/cleanup-on-gcp/tasks/main.yml
azure pruning fix in the subject https://github.com/openshift-scale/scale-ci-deploy/commit/80ea4ff31d5dcff1429c727e2797d8873f2fbe37#diff-fde0c50d2fc6976fb63965ebfef2f500R56
edge case missed
cleanup is skipped (cluster!=Running) even when the metadata files are lying around (failed install)
> reverting to old cleanup method as we have an azure pruning fix

- OCP-4.X/roles/cerberus_install/tasks/main.yml
We need to check if there exists a container named `cerberus`. 
```
root@ip-172-31-49-29: ~ # podman ps | grep -w cerberus || podman ps -a | grep -w cerberus
70151f8b91ea  quay.io/openshift-scale/cerberus:latest  /bin/sh -c python...  3 weeks ago   Exited (1) 3 weeks ago          sleepy_volhard
```
With the above command, cerberus in image name is grepped as well. Thus causing failure in the Ansible play when it tries to delete `cerberus` container which doesn't exist.
> Fixes bug associated with command to check if ceberus is running

- OCP-4.X/roles/install-on-aws/tasks/main.yml
- OCP-4.X/roles/install-on-azure/tasks/main.yml
- OCP-4.X/roles/install-on-gcp/tasks/main.yml
JQ is needed by the installer and isn't listed in the package requirements. I also standardized them across the cloud roles.
> Standardizing packages across the roles and adding in jq as a package

- OCP-4.X/roles/install-on-aws/tasks/main.yml
- OCP-4.X/roles/install-on-azure/tasks/main.yml
- OCP-4.X/roles/install-on-gcp/tasks/main.yml
- OCP-4.X/roles/install-on-osp/tasks/main.yml
Adding `remote_src` to copying the log
> Fix log copy

- OCP-4.X/roles/post-install/tasks/main.yml
Dittybopper has been merged with arsenal at https://github.com/cloud-bulldozer/performance-dashboards.git
> Update dittybopper URL

- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/roles/post-install/templates/aws-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/aws-workload-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/azure-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/azure-workload-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/gcp-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/gcp-workload-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/osp-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/osp-workload-node-machineset.yml.j2
The old name is not valid anymore, updating it to `worker-user-data-managed`
> Updating userDataSecret name from machinesets

- OCP-4.X/roles/data_server_install/tasks/main.yml
- OCP-4.X/vars/install-on-aws.yml
- OCP-4.X/vars/install-on-azure.yml
- OCP-4.X/vars/install-on-gcp.yml
- OCP-4.X/vars/install-on-osp.yml
- docs/ocp4_aws.md
- docs/ocp4_azure.md
- docs/ocp4_gcp.md
- docs/ocp4_osp.md
Update data server installation to reflect changes in data server dependencies, podman for orchestration, and [snappy cli](https://github.com/mfleader/snappyCLI). Newest version of the [data server](https://github.com/mfleader/snappy-data-server/tree/auth-sqa) uses a postgres service container to store user information for authentication.
The commit changes looks a little weird because the first version used docker. That one was squashed for this version which uses podman.
> Data server

- OCP-4.X/build-info-inventory.example
- OCP-4.X/build-info.yml
This commit enables build trigger to check the cluster state and
set the status for the install jobs to query in addition to the
build info and act accordingly.
> Add support to build trigger to capture cluster state

- OCP-4.X/roles/install-on-aws/tasks/main.yml
> Dont require sudo when reading ssh public key

- OCP-4.X/roles/install-on-aws/tasks/main.yml
This is an effort to make sure all the packages used by post-install
are installed on the orchestration host to rely less on the AMI. The
orchestration host after this change just needs keys and ansible installed
to run the install/post-steps.
> Bake in additional dependencies

- OCP-4.X/build-info.yml
- OCP-4.X/vars/build-info.yml
as we no longer have kubeconfig in ~/.kube we need an env var
> add kubeconfig var for build-info

- OCP-4.X/clean-on-osp.yml
- OCP-4.X/deploy-cluster.yml
- OCP-4.X/install-on-osp.yml
- OCP-4.X/roles/cerberus_install/tasks/main.yml
- OCP-4.X/roles/install-on-osp/tasks/main.yml
- OCP-4.X/roles/openshift-cleanup/tasks/main.yml
- OCP-4.X/roles/openshift-install/tasks/main.yml
- OCP-4.X/roles/post-install/tasks/main.yml
Replace scale_ci_deploy_directory with dynamic_deploy_path.
Now dynamic_deploy_path is set in an Ansible pre-task (before executing any role).
The expression to set dynamic_deploy_path has been updated to:
```yaml
- name: Set dynamic scale-ci-deploy path
set_fact:
dynamic_deploy_path: "{% if lookup('env', 'DYNAMIC_DEPLOY_PATH') %}{{ lookup('env', 'DYNAMIC_DEPLOY_PATH') }}{% else %}scale-ci-{{ openshift_cluster_name }}-{{ platform }}{% endif %}"
```
Wich will use DYNAMIC_DEPLOY_PATH env var value if set or `scale-ci-{{ openshift_cluster_name }}-{{ platform }}{`
> Fix dynamic deploy path

- OCP-4.X/clean-on-osp.yml
- OCP-4.X/roles/openshift-cleanup/tasks/main.yml
Cleanup contents from bin directory only
Fixes # (issue)
Will prevent scale-ci-deploy to hang when cleanup is executed (bin directory was deleted so it cant extract install binaries in there)
> Cleanup bin

- OCP-4.X/clean-on-osp.yml
- OCP-4.X/roles/openshift-cleanup/tasks/main.yml
We need to use dynamic_deploy_path to actually remove the bin directory
> Use dynamic_deploy_path to cleanup bin directory

- OCP-4.X/roles/post-install/templates/aws-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/aws-workload-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/azure-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/azure-workload-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/gcp-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/gcp-workload-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/osp-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/osp-workload-node-machineset.yml.j2
The infra/workload machinesets we create currently have the format of $CLUSTER_NAME-$MACHINESET_NAME which can cause issues for underlying machines if the cluster name is long enough. Since the machinesets/machines get labeled with the cluster name there's not a great reason to prepend the name to the resources (the aws infra machinesets already don't do it)
> removing cluster-name from machineset names

- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/roles/post-install/templates/gcp-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/gcp-workload-node-machineset.yml.j2
The current implementation doesn't get us infra and workload node as the image is not available.
This commit copies the image from worker machineset
> add worker node machineset image to infra and workload node

- CI/run_ci.sh
- OCP-4.X/roles/openshift-install/tasks/main.yml
The retry mechanism is required for oc client tools as well , since the mirror.openshift.com hosting the openshift-client has the same optimization technique as for the binary tarball
> Retry mechanism for oc client tools 

- docs/aws-example.sh
- docs/ocp4_aws.md
- docs/ocp4_azure.md
- docs/ocp4_gcp.md
- docs/ocp4_osp.md
Usage given in docs does not match the usage in the README. Docs specify running a distinct playbook per cloud provider, rather than configuring a var file and given a ``platform`` env variable. 
Documentation to match usage under README.
> Refactor deploy docs to match usage in README

- OCP-4.X/roles/openshift-install/tasks/main.yml
Deploy playbook will fail on AWS with a message like ``Destination directory /root/.aws does not exist`` if the AWS configuration is not setup for the root user ahead of time.
Adds a task to create a ``.aws`` directory under the ``ansible_user_dir``. This is similar method for Azure config, as there exists a task in this file for creating ``.azure`` before writing the client config.
> Add task to ensure .aws directory exists before writing config

- OCP-4.X/roles/rhacs_install/tasks/main.yml
When ACS deploy happens from the same jump host where it ran before it fails due to the previous install bundle file.
Remove the bundle file prior to deploy.
> ACS: Handle repeat runs

- OCP-4.X/roles/post-install/templates/aws-workload-node-machineset.yml.j2
- OCP-4.X/vars/install-on-aws.yml
- docs/ocp4_aws.md
Signed-off-by: Kedar Vijay Kulkarni <kkulkarni@redhat.com>
Making Scale ci deploy accept a `workload_aws_az_suffix` variable to allow specifying what suffix to use for az. It can accept single letter value e.g. `a`,`b`,`c` etc. Applies only to workload node machineset.
This fixes the issue where scale-ci-deploy is assuming that workload nodes should be in a different AZ - but not all regions have an AZ `d`. E.g. `us-east-2d` doesn't exist.
> Adding AZ param to workload node machineset for aws

- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/roles/post-install/templates/cluster-monitoring-config.yml.j2
- OCP-4.X/vars/install-common-vars.yml
- docs/ocp4_common_env_var.md
Adds the ability to remote_write to a thanos receiver with appropriate external labels. 
Dag running with these changes here: http://whitleykeith-thanos-airflow.apps.sailplane.perf.lab.eng.rdu2.redhat.com/log?dag_id=4.8_aws_default&task_id=install&execution_date=2021-07-28T15%3A42%3A44.940964%2B00%3A00
> Thanos Support

- OCP-4.X/roles/rhacs_install/tasks/main.yml
- OCP-4.X/vars/install-common-vars.yml
- docs/ocp4_common_env_var.md
As per title, with this change the main ACS image version can be specified in order to test non-latest candidates.
> ACS: allow the main image source to be specified

- OCP-4.X/roles/post-config-on-azure/tasks/main.yml
- OCP-4.X/vars/install-on-azure.yml
- docs/ocp4_azure.md
Signed-off-by: Kedar Vijay Kulkarni <kkulkarni@redhat.com>
Cluster expiry was set to lengthy 40 days period, unknowingly, a test cluster remaining running could cost thousands of :dollar: to us, reducing it to 7 days with an option to make it even shorter if needed by defining the variable.
@mohit-sheth @jtaleric
> Reducing clusterexpiry to 7 days

- OCP-4.X/roles/openshift-install/tasks/main.yml
This way if we need a build other than the latest nightly, it can be overridden in airflow
> have image_override be of higher precedence than binary_url

- OCP-4.X/roles/openshift-install/tasks/main.yml
As we have multiple clusters on the same jump host the oc client location is common for all of them. The copy command will fail wth "Text file busy" if we are running some command in the background.
The -f option will force the copy
> force copy oc clients to avoid 'text file busy'

- OCP-4.X/roles/post-install/templates/gcp-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/gcp-workload-node-machineset.yml.j2
https://github.com/cloud-bulldozer/scale-ci-deploy/issues/169
https://github.com/cloud-bulldozer/scale-ci-deploy/issues/170
From To Hung in QE team:
> We do see this problem (firewall not cleaned up) when a machine is created using yaml especially if the machine does not have a name that matches the cluster infra id.
> Most, if not all, of our automation do not create machine using a yaml.
So If we include cluster infra id to the machine name, both the firewall and storage issues could be fixed.
https://github.com/cloud-bulldozer/scale-ci-deploy/pull/171 did a change to include cluster-name in name of gcp infra and workload machinesets, but the cluster-name is in the middle.
After reading https://coreos.slack.com/archives/C68TNFWA2/p1631654865169700?thread_ts=1631629766.139500&cid=C68TNFWA …
> move cluster name to the begining of gcp infra and workload machinesets

- OCP-4.X/roles/post-config-on-osp/tasks/main.yml
use infra id to filter security group, so we will use the exact security group created.
> use infra id to filter security group

- OCP-4.X/roles/post-install/defaults/main.yml
- OCP-4.X/roles/post-install/files/sbdb-relay.sh
- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/vars/install-common-vars.yml
- docs/ocp4_aws.md
In order to test the sbdb relay functionality.
- Adds sbdb relay functionality
- Create `post-install` default vars
- Small related changes
> Add ovn-sbdb-relay deployment to post-install

- OCP-4.X/roles/cerberus_install/templates/cerberus.j2
set kubeconfig_path to string /root/.kube/config, instead of a variable, since kubeconfig_path is always mounted to  /root/.kube/config in podman.
Fixes cloud-bulldozer/scale-ci-deploy/issues/180
> set  kubeconfig_path to string constant

- OCP-4.X/roles/post-config-on-aws/tasks/main.yml
- OCP-4.X/roles/post-config-on-azure/tasks/main.yml
- OCP-4.X/roles/post-config-on-gcp/tasks/main.yml
- OCP-4.X/roles/post-config-on-osp/tasks/main.yml
Create security groups for port range 20000-30109 rather than the original 20000-20109 in order to make NodePort services work. We need this PR to be merged before https://github.com/cloud-bulldozer/benchmark-wrapper/pull/402
cc: @josecastillolema
> Open port range 20000-30109

- OCP-4.X/roles/post-install/files/index-install-timings.py
- OCP-4.X/roles/post-install/tasks/main.yml
The current script for indexing install timings in post-install was broken and some of the important data points are not being indexed.
Rewrite install time parsing from log file in python.
> rewrite and fix indexing cluster-install-timings

- OCP-4.X/roles/openshift-install/tasks/main.yml
The directory for credentials is not alibaba. Also preventing extracting the aliyun binary there
> Create  ~/.alibabacloud directory instean ~/.alibaba

- OCP-4.X/roles/post-install/files/index-install-timings.py
We have enabled TLS in ES and it's using a self-signed cert
> Disable cert verification in install timings indexing

- OCP-4.X/roles/post-config-on-alibaba/tasks/main.yml
- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/roles/post-install/templates/alibaba-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/alibaba-workload-node-machineset.yml.j2
ansible throws an error - no property stdout found. for the Alibaba region var which is registered in the post-install step.
Reusing the var from env for the fix.
> remove task for fetching alibaba region in post install

- OCP-4.X/roles/post-config-on-alibaba/tasks/main.yml
- OCP-4.X/roles/post-config-on-aws/tasks/main.yml
- OCP-4.X/roles/post-config-on-azure/tasks/main.yml
- OCP-4.X/roles/post-config-on-gcp/tasks/main.yml
- OCP-4.X/roles/post-config-on-osp/tasks/main.yml
When  openshift_toggle_workload_node=true and openshift_debug_config=false
The workload machineset will be created, but, the created workload node won't be added to the dynamic inventory
Therefore, these tasks will be skipped
https://github.com/cloud-bulldozer/scale-ci-deploy/blob/master/OCP-4.X/deploy-cluster.yml#L58-L131
This is required for alibaba cloud deployments, since at the moment it's not possible to assign a public IP to the created instances.
> Don't add workload node when openshift_debug_config is false

- OCP-4.X/roles/openshift-install/templates/install-config-alibaba.yaml.j2
- OCP-4.X/roles/post-install/templates/alibaba-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/alibaba-workload-node-machineset.yml.j2
- OCP-4.X/vars/install-on-alibaba.yml
Alibaba cloud has limitations on the number of resource groups. At present we are creating a new resource group on every install which causes quota issues.
Changing it to use the pre-existing default resource group.
> add default resourcegroup id for alibaba

- OCP-4.X/roles/openshift-cleanup/tasks/main.yml
Will prevent errors like the following:
```
[2022-04-21, 19:11:37 EDT] {subprocess.py:89} INFO - fatal: [ec2-34-220-44-1.us-west-2.compute.amazonaws.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'alibaba_region' is undefined\n\nThe error appears to be in '/home/airflow/workspace/scale-ci-deploy/OCP-4.X/roles/openshift-cleanup/tasks/main.yml': line 12, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n    - name: Cleanup cluster\n      ^ here\n"}
```
cc: @amitsagtani97
> Default value for alibaba_region

- OCP-4.X/roles/openshift-install/templates/install-config-gcp.yaml.j2
- OCP-4.X/roles/post-install/templates/gcp-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/gcp-workload-node-machineset.yml.j2
- OCP-4.X/vars/install-on-gcp.yml
We're using instance_type in airflow rather than machine_type
https://github.com/cloud-bulldozer/airflow-kubernetes/blob/07cd0814fe09583b6cf451f701d405ba1cb73a86/dags/openshift_nightlies/config/install/gcp/ovn.json#L17
> Replace machine_type by instance_type

- OCP-4.X/deploy-cluster.yml
- OCP-4.X/destroy-cluster.yml
- OCP-4.X/roles/openshift-install/defaults/main.yml
- OCP-4.X/roles/openshift-install/tasks/main.yml
- OCP-4.X/roles/openshift-install/templates/install-config-aws.yaml.j2
- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/vars/install-on-aws.yml
scale-ci-deploy changes required to run airflow-kubernetes tests against AWS Graviton2 instances.
See the branch of the same name.
> PERFSCALE-1816 - Enables AWS Graviton2 tests.

- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/roles/post-install/templates/alibaba-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/aws-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/azure-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/gcp-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/osp-infra-node-machineset.yml.j2
We no longer need 3 infra nodes. We needed it originally b/c alertManager had 3 replicas, now it has 2.
cc: @jtaleric @dry923
> Deploy 2 infra nodes rather than 3

- OCP-4.X/vars/install-common-vars.yml
Fixes: aa9b4c5d45a6 ("Allow deploying custom CNO image with openshift_cno_image")
> common-vars: add missing CNO patch definitions

- OCP-4.X/roles/post-install/tasks/main.yml
Currently we can't patch cno alone as it depends on openshift_ovn_image.
This patch allow below combination of patching cno and ovn images
1. apply only ovnk image
2. apply only cno image (this is the way to enable ic on nightly)
3. apply both ovnk and cno image
> patch ovn and cno images independently

- OCP-4.X/roles/post-install/tasks/main.yml
Instead of ovnkube-master and ovnkube-node, it's now a single ovnkube-controller container.
> Update OVN image patching for combined ovnkube container
