- README.md
Update github repo for scale-ci-deploy to point to openshift-scale.
> Fix repo location

- OCP-4.X/scale.yml
Also evenly distribute the "extra" instances across AZs
> Adjust 4.X scale playbook to work with 4 availability zones

- OCP-4.X/install-on-azure.yml
- OCP-4.X/roles/cleanup-on-azure/tasks/main.yml
- OCP-4.X/roles/install-on-azure/tasks/main.yml
- OCP-4.X/roles/install-on-azure/templates/install-config.yaml.j2
- OCP-4.X/roles/install-on-azure/templates/osServicePrincipal.json.j2
- OCP-4.X/roles/install-on-azure/templates/registry_auth.j2
- OCP-4.X/roles/node-debug-config-on-azure/tasks/main.yml
- OCP-4.X/roles/post-config-on-azure/tasks/main.yml
- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/roles/post-install/templates/aws-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/aws-workload-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/azure-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/azure-workload-node-machineset.yml.j2
- OCP-4.X/vars/install-on-azure.yml
WIP thus DNM, however please review when time is available.
> Add Azure IPI install

- OCP-4.X/scale.yml
- docs/ocp4_scale.md
> Remove unused task

- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/vars/install-on-aws.yml
- OCP-4.X/vars/install-on-azure.yml
- OCP-4.X/vars/install-on-gcp.yml
- OCP-4.X/vars/install-on-osp.yml
- docs/ocp4_aws.md
- docs/ocp4_azure.md
- docs/ocp4_gcp.md
- docs/ocp4_osp.md
Using sincgars enable remote write as day 2 ops.
> Added logic to enable remote write

- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/vars/install-on-aws.yml
- OCP-4.X/vars/install-on-azure.yml
- OCP-4.X/vars/install-on-gcp.yml
- OCP-4.X/vars/install-on-osp.yml
- docs/ocp4_aws.md
- docs/ocp4_azure.md
- docs/ocp4_gcp.md
- docs/ocp4_osp.md
This will allow us to deploy mutable Grafana with some preloaded
dashboards
Also, looks like someone added some extra spaces :dagger:
> Adding support for Dittybopper

- OCP-4.X/roles/post-config-on-gcp/tasks/main.yml
There was an indentation issue with gcp, this commit fixes it
> fixing indentation issues

- OCP-4.X/roles/cerberus_install/templates/cerberus.j2
- OCP-4.X/vars/install-on-aws.yml
- OCP-4.X/vars/install-on-azure.yml
- OCP-4.X/vars/install-on-gcp.yml
- OCP-4.X/vars/install-on-osp.yml
- docs/ocp4_aws.md
- docs/ocp4_azure.md
- docs/ocp4_gcp.md
- docs/ocp4_osp.md
Added new variables in the cerberus template.
> Updating cerberus template

- OCP-4.X/roles/install-on-aws/templates/install-config.yaml.j2
- OCP-4.X/roles/install-on-azure/templates/install-config.yaml.j2
- OCP-4.X/roles/install-on-gcp/templates/install-config.yaml.j2
- OCP-4.X/roles/install-on-osp/templates/install-config.yaml.j2
- OCP-4.X/vars/install-on-aws.yml
- OCP-4.X/vars/install-on-azure.yml
- OCP-4.X/vars/install-on-gcp.yml
- OCP-4.X/vars/install-on-osp.yml
Allow user to deploy with FIPs
> Adding FIPs

- OCP-4.X/roles/install-on-aws/tasks/main.yml
- OCP-4.X/roles/install-on-azure/tasks/main.yml
- OCP-4.X/roles/install-on-gcp/tasks/main.yml
- OCP-4.X/roles/install-on-osp/tasks/main.yml
- OCP-4.X/roles/post-install/files/index-install-data.sh
- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/vars/install-on-aws.yml
- OCP-4.X/vars/install-on-azure.yml
- OCP-4.X/vars/install-on-gcp.yml
- OCP-4.X/vars/install-on-osp.yml
Allow the post-tasks to index install results
> Adding script to index install results

- OCP-4.X/roles/post-install/files/index-install-data.sh
> Fixing index

- OCP-4.X/roles/post-install/files/index-install-data.sh
Index metadata describing SUT before indexing install data
> Adding Backpack collection for metadata

- OCP-4.X/roles/post-install/files/index-install-data.sh
- OCP-4.X/vars/install-on-aws.yml
- OCP-4.X/vars/install-on-azure.yml
- OCP-4.X/vars/install-on-gcp.yml
- OCP-4.X/vars/install-on-osp.yml
eliminate ES_SERVER and use regex to trim down already supplied ELASTIC_CURL_URL by the user
added port 80 to default so that backpack can use it is -p 80
> fix index install timings

- OCP-4.X/roles/post-install/files/index-install-data.sh
Allow passing ESUSER to run_backpack when it is not ""
> Updating to allow user/pass to be provided to run_backpack

- OCP-4.X/roles/post-install/files/index-install-data.sh
Adding SSL option for the pipeline
> SSL for pipeline

- .gitignore
- OCP-4.X/roles/post-install/files/index-install-data.sh
- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/vars/install-common-vars.yml
Depends on: https://github.com/cloud-bulldozer/metadata-collector/pull/23
> Deprecate ELASTIC_USER

- OCP-4.X/roles/post-install/tasks/main.yml
> Add KUBECONFIG to performance-dashboard install task

- OCP-4.X/roles/openshift-install/tasks/main.yml
- OCP-4.X/roles/post-config-on-aws/tasks/main.yml
- OCP-4.X/roles/post-config-on-azure/tasks/main.yml
- OCP-4.X/roles/post-config-on-gcp/tasks/main.yml
- OCP-4.X/roles/post-config-on-osp/tasks/main.yml
- OCP-4.X/roles/post-install/tasks/main.yml
For osp we are having config file at some static location defined in the properties file.
> updated kubeconfig for post_install in osp

- OCP-4.X/clean-on-osp.yml
- OCP-4.X/roles/cerberus_install/tasks/main.yml
- OCP-4.X/roles/install-on-osp/tasks/main.yml
- OCP-4.X/roles/openshift-cleanup/tasks/main.yml
- OCP-4.X/roles/openshift-install/tasks/main.yml
- OCP-4.X/roles/post-install/tasks/main.yml
- When installed from install scripts, it will create a dynamic path.
- When using individual scripts, it will pick the static path if the dynamic path doesn't exist.
> added support for both static and dynamic path

- OCP-4.X/clean-on-osp.yml
- OCP-4.X/roles/openshift-cleanup/tasks/main.yml
Quick fix for cleanup expression
> Fix cleanup with_items expression

- OCP-4.X/roles/cerberus/tasks/main.yml
Adding retries to Cerberus Status check
No issue tracking this.
> Cerberus failures in CI

- OCP-4.X/roles/cerberus/tasks/main.yml
> Modify the cerberus check to wait for True signal

- CI/run_ci.sh
- OCP-4.X/roles/openshift-install/tasks/main.yml
extract the binary baseurl from openshift install binary url and poll the openshift server to come back to life 
needed update on pr : https://github.com/cloud-bulldozer/scale-ci-deploy/pull/55
@chaitanyaenr @jtaleric
> retry mechanism for openshift install payload

- CI/run_ci.sh
- OCP-4.X/roles/openshift-install/tasks/main.yml
> update to make the playbook fail on error in the extract openshift-binary step

- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/vars/install-common-vars.yml
> Allow post-install to change the OVNK Image for dev

- OCP-4.X/roles/post-install/templates/aws-workload-node-machineset.yml.j2
Missed adding the parameter in 2 other places in the previous PR. Adding it here. @mohit-sheth can you please review.
> Add parameter to replace remaining hard-coded 'd'

- OCP-4.X/vars/install-on-aws.yml
Signed-off-by: Kedar Vijay Kulkarni <kkulkarni@redhat.com>
@whitleykeith pointed out missing "default" in the vars file. Adding it. @mohit-sheth please review. Thank you both :)
> Defaulting the suffix to 'd' to avoid installation issues with empty var

- OCP-4.X/roles/post-install/templates/gcp-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/gcp-workload-node-machineset.yml.j2
Will fix the disks that are hanging around even after cleanup
> autodelete the disks once the attached nodes are cleaned up

- OCP-4.X/roles/post-config-on-osp/tasks/main.yml
> fix infra id output

- OCP-4.X/deploy-cluster.yml
- OCP-4.X/roles/openshift-install/tasks/main.yml
- OCP-4.X/roles/openshift-install/templates/alibaba_credentials.j2
- OCP-4.X/roles/openshift-install/templates/install-config-alibaba.yaml.j2
- OCP-4.X/roles/post-config-on-alibaba/tasks/main.yml
- OCP-4.X/roles/post-install/tasks/main.yml
- OCP-4.X/roles/post-install/templates/alibaba-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/alibaba-workload-node-machineset.yml.j2
- OCP-4.X/vars/install-on-alibaba.yml
- README.md
- docs/README.md
- docs/ocp4_alibaba.md
Add cluster installation on Alibaba cloud
#TODO
> Add support for Alibaba cloud

- OCP-4.X/roles/openshift-cleanup/tasks/main.yml
> Remove manually created alibaba RAM users in cleanup role

- OCP-4.X/roles/openshift-cleanup/tasks/main.yml
> Set KUBECONFIG env var in delete

- OCP-4.X/roles/rhacs_install/tasks/main.yml
The install process has changed such that the existing ACS install failed. This PR fixes that and defaults the install to the nightly build.
Tested manually and in airflow playground.
> Fix ACS install

- OCP-4.X/roles/openshift-install/templates/install-config-aws.yaml.j2
- OCP-4.X/vars/install-on-aws.yml
Adding a `use` tag (for AWS) so we can determine where costs are coming from (who or what).
Signed-off-by: Joe Talerico (rook) <joe.talerico@gmail.com>
> Adding kv for aws

- OCP-4.X/roles/post-config-on-alibaba/tasks/main.yml
- OCP-4.X/roles/post-config-on-aws/tasks/main.yml
- OCP-4.X/roles/post-config-on-azure/tasks/main.yml
- OCP-4.X/roles/post-config-on-gcp/tasks/main.yml
- OCP-4.X/roles/post-config-on-osp/tasks/main.yml
Updating the range to cover more tools
> Opening up ports for network performance

- OCP-4.X/roles/post-install/tasks/main.yml
Like we do for OVN-Kube images.
> Allow deploying custom CNO image with openshift_cno_image

- OCP-4.X/roles/openshift-install/templates/install-config-aws.yaml.j2
This PR updates the tags from use: --> User:
allowing for relevant cloud spend tracking
- Related Issue #
- Closes #
- Please describe the System Under Test - NA
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results - Minor fix, updating tag details accordingly.
> Updates tagging convention

- OCP-4.X/roles/openshift-cleanup/tasks/main.yml
- OCP-4.X/roles/openshift-install/defaults/main.yml
- OCP-4.X/roles/openshift-install/tasks/main.yml
- OCP-4.X/roles/post-config-on-aws/tasks/main.yml
- OCP-4.X/vars/install-on-aws.yml
AWS shared credential file path to use a different aws authentication file
- Related Issue #
- Closes #
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.
> AWS shared credentials file

- OCP-4.X/vars/install-common-vars.yml
Removing Dev ES from the source code references.
- Closes # https://issues.redhat.com/browse/PERFSCALE-3430
> Removing Dev ES references

- OCP-4.X/roles/post-install/templates/aws-infra-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/aws-workload-node-machineset.yml.j2
- OCP-4.X/roles/post-install/templates/cluster-monitoring-config.yml.j2
Names of some AWS resources change in 4.16.
We need these changes in order for infra and workload nodes to deploy correctly.
> Updates to aws resources for 4.16
